product-maintainers:
  members:
    - jjscarafia
    - JordiBForgeFlow
    - rousseldenis
    - legalsylvain
  name: Product maintainers
  representatives:
    - gurneyalex
product-maintainers-psc-representative:
  members: []
  name: Product maintainers psc representative
  representatives: []
