name: Update repos

on:
  push:
    branches:
      - "master"
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install requirements
        run: pip install pip install https://github.com/OCA/repo-maintainer/archive/master.zip
      - name: Manage repositories
        run:
          oca-repo-manage --org $GITHUB_REPOSITORY_OWNER --token ${{secrets.GIT_PUSH_TOKEN}} --conf-dir ./conf
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update checksum
          file_pattern: "conf/checksum.yml"
          commit_user_name: OCA-git-bot
          commit_user_email: oca-git-bot@odoo-community.org
          commit_author: OCA-git-bot <oca-git-bot@odoo-community.org>

